// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmoFuO4XPqmZ7BlnLFgtffJV31emNw2N4',
    appId: '1:500963533087:web:355adb0b5b13d4917a502a',
    messagingSenderId: '500963533087',
    projectId: 'taskify-71f3f',
    authDomain: 'taskify-71f3f.firebaseapp.com',
    storageBucket: 'taskify-71f3f.appspot.com',
    measurementId: 'G-Q31LF17X1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzr-8v88LAEz6_VG_9lp_Cu6Bz8EBpJNo',
    appId: '1:500963533087:android:c0e2d1cb270b2bfe7a502a',
    messagingSenderId: '500963533087',
    projectId: 'taskify-71f3f',
    storageBucket: 'taskify-71f3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANKW9No-opaJcuu8chLxf2IUQA-G7mWUw',
    appId: '1:500963533087:ios:7c9d0217f58bb60c7a502a',
    messagingSenderId: '500963533087',
    projectId: 'taskify-71f3f',
    storageBucket: 'taskify-71f3f.appspot.com',
    iosClientId: '500963533087-gqahga9khes839bti7648umj590vdchc.apps.googleusercontent.com',
    iosBundleId: 'com.innoscripta.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANKW9No-opaJcuu8chLxf2IUQA-G7mWUw',
    appId: '1:500963533087:ios:7c9d0217f58bb60c7a502a',
    messagingSenderId: '500963533087',
    projectId: 'taskify-71f3f',
    storageBucket: 'taskify-71f3f.appspot.com',
    iosClientId: '500963533087-gqahga9khes839bti7648umj590vdchc.apps.googleusercontent.com',
    iosBundleId: 'com.innoscripta.taskify',
  );
}
